default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0


development:
  <<: *default
  database: bodymake_development

test:
  <<: *default
  database: bodymake_test

production:
  <<: *default
  database: bodymake_production
  username: bodymake
  password: <%= ENV['bodymake_DATABASE_PASSWORD'] %>
